// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD_310_W22SD_Assignment.Models;

#nullable disable

namespace SD_310_W22SD_Assignment.Migrations
{
    [DbContext(typeof(MySpotifyDBContext))]
    [Migration("20220723042121_AddWalletToUsers")]
    partial class AddWalletToUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("MusicId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MusicId");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Music", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int?>("SongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("SongId");

                    b.ToTable("Music", (string)null);
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float?>("Wallet")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Collection", b =>
                {
                    b.HasOne("SD_310_W22SD_Assignment.Models.Music", "Music")
                        .WithMany("Collections")
                        .HasForeignKey("MusicId")
                        .HasConstraintName("FK_Collections_Music");

                    b.HasOne("SD_310_W22SD_Assignment.Models.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Collections_Users");

                    b.Navigation("Music");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Music", b =>
                {
                    b.HasOne("SD_310_W22SD_Assignment.Models.Artist", "Artist")
                        .WithMany("Musics")
                        .HasForeignKey("ArtistId")
                        .HasConstraintName("FK_Music_Artists");

                    b.HasOne("SD_310_W22SD_Assignment.Models.Song", "Song")
                        .WithMany("Musics")
                        .HasForeignKey("SongId")
                        .HasConstraintName("FK_Music_Songs");

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Artist", b =>
                {
                    b.Navigation("Musics");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Music", b =>
                {
                    b.Navigation("Collections");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Song", b =>
                {
                    b.Navigation("Musics");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.User", b =>
                {
                    b.Navigation("Collections");
                });
#pragma warning restore 612, 618
        }
    }
}
